# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-10 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='introduce',
            field=models.CharField(default='no introduce', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='xxx@xx.com', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='xxxxxx', max_length=128),
        ),
    ]
